{
 "title": "Observabily Playground",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(request_latency_bucket[5m])) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(total_requests{status=~\"2..\"}[5m]))\r\n/\r\nsum(rate(total_requests[5m]))\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(total_requests{status=~\"4..\"}[5m]))\r\n/\r\nsum(rate(total_requests[5m]))\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(total_requests{status=~\"5..\"}[5m])) * 100) / (sum(rate(total_requests[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"observability-playground\"}\r\n| json\r\n| keep ts, level, method, path, status"
    }
   ]
  },
  {
   "title": "Trace",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "filters": [
      { "id": "2e648a6f", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  }
 ]
}