// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type Product struct {
	ID        int64
	Name      string
	Quantity  int64
	Price     float64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
